// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCq8AwoGUmVzdWx0EgsKB1NVQ0NFU1MQ",
            "ABIKCgZGQUlMRUQQARIXChNTVUNDRVNTX1JPT01fQ1JFQVRFEAISFwoTU1VD",
            "Q0VTU19ST09NX0pPSU5FRBADEhgKFFNVQ0NFU1NfR1JPVVBfQ1JFQVRFEAQS",
            "GAoUU1VDQ0VTU19HUk9VUF9KT0lORUQQBRIfChtGQUlMRURfUk9PTV9OT1Rf",
            "RVhJU1RTX1JPT00QChIjCh9GQUlMRURfUk9PTV9BTFJFQURZX0VYSVNUU19S",
            "T09NEAsSGwoXRkFJTEVEX1JPT01fTk9UX0lOX1JPT00QDBIhCh1GQUlMRURf",
            "R1JPVVBfTk9UX0VYSVNUU19HUk9VUBAUEh0KGUZBSUxFRF9HUk9VUF9OT1Rf",
            "SU5fR1JPVVAQFRIlCiFGQUlMRURfR1JPVVBfQUxSRUFEWV9FWElTVFNfR1JP",
            "VVAQFhIbChdGQUlMRURfR1JPVVBfU0FNRV9HUk9VUBAXEiIKHkZBSUxFRF9H",
            "Uk9VUF9OT1RfRVhJU1RTX1BMQVlFUhAYEiYKIkZBSUxFRF9HUk9VUF9BTFJF",
            "QURZX0VYSVNUU19QTEFZRVIQGSphCgdQcm9wc0lEEhIKDk1WX1BST1BTX1NU",
            "QVJUEAASDwoLUE9TSVRJT05fM0QQARIPCgtST1RBVElPTl8zRBACEgwKCFND",
            "QUxFXzNEEAMSEgoMTVZfUFJPUFNfRU5EEKCNBipPCg5PYmplY3RTeW5jVHlw",
            "ZRIQCgxQRVJTT05BTF9PV04QABINCglHUk9VUF9PV04QARIMCghST09NX09X",
            "ThACEg4KCkdMT0JBTF9PV04QAyq8AQoNT3BlcmF0aW9uQ29kZRIOCgpIRUFS",
            "VF9CRUFUEAASFwoTUk9PTV9KT0lOX09SX0NSRUFURRABEg4KClJPT01fTEVB",
            "VkUQAhINCglST09NX0xJU1QQAxINCglQTEFZRVJfSUQQBBIOCgpHUk9VUF9M",
            "SVNUEAUSDgoKR1JPVVBfSk9JThAGEg8KC0dST1VQX0xFQVZFEAcSDwoLUkFJ",
            "U0VfRVZFTlQQCBISCg5JTklUX1ZBUklBQkxFUxAJKqQBCglFdmVudENvZGUS",
            "FwoTT1RIRVJfQ0xJRU5UX0pPSU5FRBAAEhMKD0lOSVRJQUxfT0JKRUNUUxAB",
            "EhcKE0FERF9ORVRXT1JLX09CSkVDVFMQAhIaChZSRU1PVkVfTkVUV09SS19P",
            "QkpFQ1RTEAMSGgoWVVBEQVRFX05FVFdPUktfT0JKRUNUUxAEEhgKFENIQU5H",
            "RV9PQkpFQ1RTX09XTkVSEAUqMQoIUGFyYW1LZXkSDAoIUE9TSVRJT04QABIM",
            "CghST1RBVElPThABEgkKBVNDQUxFEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.Result), typeof(global::Protocol.PropsID), typeof(global::Protocol.ObjectSyncType), typeof(global::Protocol.OperationCode), typeof(global::Protocol.EventCode), typeof(global::Protocol.ParamKey), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 패킷 변수만 갖고는 실패 이유를 알기 어려우므로 Enum 을 통해 실패 이유를 전달
  /// 여기에 실패의 이유를 적는 Enum 을 추후에 컨텐츠 별로 추가하자.
  /// </summary>
  public enum Result {
    [pbr::OriginalName("SUCCESS")] Success = 0,
    [pbr::OriginalName("FAILED")] Failed = 1,
    /// <summary>
    /// Room 관련 성공
    /// </summary>
    [pbr::OriginalName("SUCCESS_ROOM_CREATE")] SuccessRoomCreate = 2,
    [pbr::OriginalName("SUCCESS_ROOM_JOINED")] SuccessRoomJoined = 3,
    /// <summary>
    /// Group 관련 성공
    /// </summary>
    [pbr::OriginalName("SUCCESS_GROUP_CREATE")] SuccessGroupCreate = 4,
    [pbr::OriginalName("SUCCESS_GROUP_JOINED")] SuccessGroupJoined = 5,
    /// <summary>
    /// Room 관련 에러
    /// </summary>
    [pbr::OriginalName("FAILED_ROOM_NOT_EXISTS_ROOM")] FailedRoomNotExistsRoom = 10,
    [pbr::OriginalName("FAILED_ROOM_ALREADY_EXISTS_ROOM")] FailedRoomAlreadyExistsRoom = 11,
    /// <summary>
    /// Player 가 Room 에 들어와 있지 않음
    /// </summary>
    [pbr::OriginalName("FAILED_ROOM_NOT_IN_ROOM")] FailedRoomNotInRoom = 12,
    /// <summary>
    /// Group 관련 에러
    /// </summary>
    [pbr::OriginalName("FAILED_GROUP_NOT_EXISTS_GROUP")] FailedGroupNotExistsGroup = 20,
    /// <summary>
    /// 현재 Player 가 그룹 내에 있지 않음
    /// </summary>
    [pbr::OriginalName("FAILED_GROUP_NOT_IN_GROUP")] FailedGroupNotInGroup = 21,
    /// <summary>
    /// 추가하려는 그룹이 이미 존재
    /// </summary>
    [pbr::OriginalName("FAILED_GROUP_ALREADY_EXISTS_GROUP")] FailedGroupAlreadyExistsGroup = 22,
    [pbr::OriginalName("FAILED_GROUP_SAME_GROUP")] FailedGroupSameGroup = 23,
    /// <summary>
    /// 찾는 플레이어가 존재하지 않음
    /// </summary>
    [pbr::OriginalName("FAILED_GROUP_NOT_EXISTS_PLAYER")] FailedGroupNotExistsPlayer = 24,
    /// <summary>
    /// 추가하려는 플레이어가 이미 존재
    /// </summary>
    [pbr::OriginalName("FAILED_GROUP_ALREADY_EXISTS_PLAYER")] FailedGroupAlreadyExistsPlayer = 25,
  }

  public enum PropsID {
    [pbr::OriginalName("MV_PROPS_START")] MvPropsStart = 0,
    [pbr::OriginalName("POSITION_3D")] Position3D = 1,
    [pbr::OriginalName("ROTATION_3D")] Rotation3D = 2,
    [pbr::OriginalName("SCALE_3D")] Scale3D = 3,
    [pbr::OriginalName("MV_PROPS_END")] MvPropsEnd = 100000,
  }

  public enum ObjectSyncType {
    [pbr::OriginalName("PERSONAL_OWN")] PersonalOwn = 0,
    /// <summary>
    /// 여기에 해당하는 ObjectMap이 Group이랑 Room에 추가되어야 함. 이거 움직일 수 있는 사람은 MasterClient만
    /// </summary>
    [pbr::OriginalName("GROUP_OWN")] GroupOwn = 1,
    [pbr::OriginalName("ROOM_OWN")] RoomOwn = 2,
    [pbr::OriginalName("GLOBAL_OWN")] GlobalOwn = 3,
  }

  public enum OperationCode {
    [pbr::OriginalName("HEART_BEAT")] HeartBeat = 0,
    [pbr::OriginalName("ROOM_JOIN_OR_CREATE")] RoomJoinOrCreate = 1,
    [pbr::OriginalName("ROOM_LEAVE")] RoomLeave = 2,
    [pbr::OriginalName("ROOM_LIST")] RoomList = 3,
    [pbr::OriginalName("PLAYER_ID")] PlayerId = 4,
    [pbr::OriginalName("GROUP_LIST")] GroupList = 5,
    [pbr::OriginalName("GROUP_JOIN")] GroupJoin = 6,
    [pbr::OriginalName("GROUP_LEAVE")] GroupLeave = 7,
    [pbr::OriginalName("RAISE_EVENT")] RaiseEvent = 8,
    [pbr::OriginalName("INIT_VARIABLES")] InitVariables = 9,
  }

  public enum EventCode {
    [pbr::OriginalName("OTHER_CLIENT_JOINED")] OtherClientJoined = 0,
    [pbr::OriginalName("INITIAL_OBJECTS")] InitialObjects = 1,
    [pbr::OriginalName("ADD_NETWORK_OBJECTS")] AddNetworkObjects = 2,
    [pbr::OriginalName("REMOVE_NETWORK_OBJECTS")] RemoveNetworkObjects = 3,
    [pbr::OriginalName("UPDATE_NETWORK_OBJECTS")] UpdateNetworkObjects = 4,
    [pbr::OriginalName("CHANGE_OBJECTS_OWNER")] ChangeObjectsOwner = 5,
  }

  public enum ParamKey {
    [pbr::OriginalName("POSITION")] Position = 0,
    [pbr::OriginalName("ROTATION")] Rotation = 1,
    [pbr::OriginalName("SCALE")] Scale = 2,
  }

  #endregion

}

#endregion Designer generated code
