// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Protocol.proto</summary>
  public static partial class ProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for Protocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Qcm90b2NvbC5wcm90bxIIUHJvdG9jb2waCkVudW0ucHJvdG8aDFN0cnVj",
            "dC5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90bxoeZ29vZ2xlL3By",
            "b3RvYnVmL3dyYXBwZXJzLnByb3RvIooBCgtDX09QRVJBVElPThIuCg1vcGVy",
            "YXRpb25Db2RlGAEgASgOMhcuUHJvdG9jb2wuT3BlcmF0aW9uQ29kZRIiCglm",
            "aXhlZERhdGEYAiABKAsyDy5Qcm90b2NvbC5QYWNrcxInCgpjdXN0b21EYXRh",
            "GAMgASgLMhMuUHJvdG9jb2wuQ3VzdG9tRGljItIBCgtTX09QRVJBVElPThIu",
            "Cg1vcGVyYXRpb25Db2RlGAEgASgOMhcuUHJvdG9jb2wuT3BlcmF0aW9uQ29k",
            "ZRIkCgZzZW5kZXIYAiABKAsyFC5Qcm90b2NvbC5QbGF5ZXJJbmZvEiIKCWZp",
            "eGVkRGF0YRgDIAEoCzIPLlByb3RvY29sLlBhY2tzEicKCmN1c3RvbURhdGEY",
            "BCABKAsyEy5Qcm90b2NvbC5DdXN0b21EaWMSIAoGcmVzdWx0GAUgASgOMhAu",
            "UHJvdG9jb2wuUmVzdWx0IrEBCgdTX0VWRU5UEiQKBnNlbmRlchgBIAEoCzIU",
            "LlByb3RvY29sLlBsYXllckluZm8SEQoJZXZlbnRDb2RlGAIgASgFEiIKCWZp",
            "eGVkRGF0YRgDIAEoCzIPLlByb3RvY29sLlBhY2tzEicKCmN1c3RvbURhdGEY",
            "BCABKAsyEy5Qcm90b2NvbC5DdXN0b21EaWMSIAoGcmVzdWx0GAUgASgOMhAu",
            "UHJvdG9jb2wuUmVzdWx0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protocol.EnumReflection.Descriptor, global::Protocol.StructReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.C_OPERATION), global::Protocol.C_OPERATION.Parser, new[]{ "OperationCode", "FixedData", "CustomData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.S_OPERATION), global::Protocol.S_OPERATION.Parser, new[]{ "OperationCode", "Sender", "FixedData", "CustomData", "Result" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.S_EVENT), global::Protocol.S_EVENT.Parser, new[]{ "Sender", "EventCode", "FixedData", "CustomData", "Result" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class C_OPERATION : pb::IMessage<C_OPERATION>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<C_OPERATION> _parser = new pb::MessageParser<C_OPERATION>(() => new C_OPERATION());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<C_OPERATION> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C_OPERATION() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C_OPERATION(C_OPERATION other) : this() {
      operationCode_ = other.operationCode_;
      fixedData_ = other.fixedData_ != null ? other.fixedData_.Clone() : null;
      customData_ = other.customData_ != null ? other.customData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C_OPERATION Clone() {
      return new C_OPERATION(this);
    }

    /// <summary>Field number for the "operationCode" field.</summary>
    public const int OperationCodeFieldNumber = 1;
    private global::Protocol.OperationCode operationCode_ = global::Protocol.OperationCode.HeartBeat;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.OperationCode OperationCode {
      get { return operationCode_; }
      set {
        operationCode_ = value;
      }
    }

    /// <summary>Field number for the "fixedData" field.</summary>
    public const int FixedDataFieldNumber = 2;
    private global::Protocol.Packs fixedData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Packs FixedData {
      get { return fixedData_; }
      set {
        fixedData_ = value;
      }
    }

    /// <summary>Field number for the "customData" field.</summary>
    public const int CustomDataFieldNumber = 3;
    private global::Protocol.CustomDic customData_;
    /// <summary>
    ///    repeated bytes testData = 4;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.CustomDic CustomData {
      get { return customData_; }
      set {
        customData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as C_OPERATION);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(C_OPERATION other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OperationCode != other.OperationCode) return false;
      if (!object.Equals(FixedData, other.FixedData)) return false;
      if (!object.Equals(CustomData, other.CustomData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OperationCode != global::Protocol.OperationCode.HeartBeat) hash ^= OperationCode.GetHashCode();
      if (fixedData_ != null) hash ^= FixedData.GetHashCode();
      if (customData_ != null) hash ^= CustomData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OperationCode != global::Protocol.OperationCode.HeartBeat) {
        output.WriteRawTag(8);
        output.WriteEnum((int) OperationCode);
      }
      if (fixedData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FixedData);
      }
      if (customData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CustomData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OperationCode != global::Protocol.OperationCode.HeartBeat) {
        output.WriteRawTag(8);
        output.WriteEnum((int) OperationCode);
      }
      if (fixedData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FixedData);
      }
      if (customData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CustomData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OperationCode != global::Protocol.OperationCode.HeartBeat) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OperationCode);
      }
      if (fixedData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FixedData);
      }
      if (customData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CustomData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(C_OPERATION other) {
      if (other == null) {
        return;
      }
      if (other.OperationCode != global::Protocol.OperationCode.HeartBeat) {
        OperationCode = other.OperationCode;
      }
      if (other.fixedData_ != null) {
        if (fixedData_ == null) {
          FixedData = new global::Protocol.Packs();
        }
        FixedData.MergeFrom(other.FixedData);
      }
      if (other.customData_ != null) {
        if (customData_ == null) {
          CustomData = new global::Protocol.CustomDic();
        }
        CustomData.MergeFrom(other.CustomData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OperationCode = (global::Protocol.OperationCode) input.ReadEnum();
            break;
          }
          case 18: {
            if (fixedData_ == null) {
              FixedData = new global::Protocol.Packs();
            }
            input.ReadMessage(FixedData);
            break;
          }
          case 26: {
            if (customData_ == null) {
              CustomData = new global::Protocol.CustomDic();
            }
            input.ReadMessage(CustomData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OperationCode = (global::Protocol.OperationCode) input.ReadEnum();
            break;
          }
          case 18: {
            if (fixedData_ == null) {
              FixedData = new global::Protocol.Packs();
            }
            input.ReadMessage(FixedData);
            break;
          }
          case 26: {
            if (customData_ == null) {
              CustomData = new global::Protocol.CustomDic();
            }
            input.ReadMessage(CustomData);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class S_OPERATION : pb::IMessage<S_OPERATION>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<S_OPERATION> _parser = new pb::MessageParser<S_OPERATION>(() => new S_OPERATION());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<S_OPERATION> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S_OPERATION() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S_OPERATION(S_OPERATION other) : this() {
      operationCode_ = other.operationCode_;
      sender_ = other.sender_ != null ? other.sender_.Clone() : null;
      fixedData_ = other.fixedData_ != null ? other.fixedData_.Clone() : null;
      customData_ = other.customData_ != null ? other.customData_.Clone() : null;
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S_OPERATION Clone() {
      return new S_OPERATION(this);
    }

    /// <summary>Field number for the "operationCode" field.</summary>
    public const int OperationCodeFieldNumber = 1;
    private global::Protocol.OperationCode operationCode_ = global::Protocol.OperationCode.HeartBeat;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.OperationCode OperationCode {
      get { return operationCode_; }
      set {
        operationCode_ = value;
      }
    }

    /// <summary>Field number for the "sender" field.</summary>
    public const int SenderFieldNumber = 2;
    private global::Protocol.PlayerInfo sender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.PlayerInfo Sender {
      get { return sender_; }
      set {
        sender_ = value;
      }
    }

    /// <summary>Field number for the "fixedData" field.</summary>
    public const int FixedDataFieldNumber = 3;
    private global::Protocol.Packs fixedData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Packs FixedData {
      get { return fixedData_; }
      set {
        fixedData_ = value;
      }
    }

    /// <summary>Field number for the "customData" field.</summary>
    public const int CustomDataFieldNumber = 4;
    private global::Protocol.CustomDic customData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.CustomDic CustomData {
      get { return customData_; }
      set {
        customData_ = value;
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 5;
    private global::Protocol.Result result_ = global::Protocol.Result.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as S_OPERATION);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(S_OPERATION other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OperationCode != other.OperationCode) return false;
      if (!object.Equals(Sender, other.Sender)) return false;
      if (!object.Equals(FixedData, other.FixedData)) return false;
      if (!object.Equals(CustomData, other.CustomData)) return false;
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OperationCode != global::Protocol.OperationCode.HeartBeat) hash ^= OperationCode.GetHashCode();
      if (sender_ != null) hash ^= Sender.GetHashCode();
      if (fixedData_ != null) hash ^= FixedData.GetHashCode();
      if (customData_ != null) hash ^= CustomData.GetHashCode();
      if (Result != global::Protocol.Result.Success) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OperationCode != global::Protocol.OperationCode.HeartBeat) {
        output.WriteRawTag(8);
        output.WriteEnum((int) OperationCode);
      }
      if (sender_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Sender);
      }
      if (fixedData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FixedData);
      }
      if (customData_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CustomData);
      }
      if (Result != global::Protocol.Result.Success) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OperationCode != global::Protocol.OperationCode.HeartBeat) {
        output.WriteRawTag(8);
        output.WriteEnum((int) OperationCode);
      }
      if (sender_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Sender);
      }
      if (fixedData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FixedData);
      }
      if (customData_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CustomData);
      }
      if (Result != global::Protocol.Result.Success) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OperationCode != global::Protocol.OperationCode.HeartBeat) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OperationCode);
      }
      if (sender_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Sender);
      }
      if (fixedData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FixedData);
      }
      if (customData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CustomData);
      }
      if (Result != global::Protocol.Result.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(S_OPERATION other) {
      if (other == null) {
        return;
      }
      if (other.OperationCode != global::Protocol.OperationCode.HeartBeat) {
        OperationCode = other.OperationCode;
      }
      if (other.sender_ != null) {
        if (sender_ == null) {
          Sender = new global::Protocol.PlayerInfo();
        }
        Sender.MergeFrom(other.Sender);
      }
      if (other.fixedData_ != null) {
        if (fixedData_ == null) {
          FixedData = new global::Protocol.Packs();
        }
        FixedData.MergeFrom(other.FixedData);
      }
      if (other.customData_ != null) {
        if (customData_ == null) {
          CustomData = new global::Protocol.CustomDic();
        }
        CustomData.MergeFrom(other.CustomData);
      }
      if (other.Result != global::Protocol.Result.Success) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OperationCode = (global::Protocol.OperationCode) input.ReadEnum();
            break;
          }
          case 18: {
            if (sender_ == null) {
              Sender = new global::Protocol.PlayerInfo();
            }
            input.ReadMessage(Sender);
            break;
          }
          case 26: {
            if (fixedData_ == null) {
              FixedData = new global::Protocol.Packs();
            }
            input.ReadMessage(FixedData);
            break;
          }
          case 34: {
            if (customData_ == null) {
              CustomData = new global::Protocol.CustomDic();
            }
            input.ReadMessage(CustomData);
            break;
          }
          case 40: {
            Result = (global::Protocol.Result) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OperationCode = (global::Protocol.OperationCode) input.ReadEnum();
            break;
          }
          case 18: {
            if (sender_ == null) {
              Sender = new global::Protocol.PlayerInfo();
            }
            input.ReadMessage(Sender);
            break;
          }
          case 26: {
            if (fixedData_ == null) {
              FixedData = new global::Protocol.Packs();
            }
            input.ReadMessage(FixedData);
            break;
          }
          case 34: {
            if (customData_ == null) {
              CustomData = new global::Protocol.CustomDic();
            }
            input.ReadMessage(CustomData);
            break;
          }
          case 40: {
            Result = (global::Protocol.Result) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class S_EVENT : pb::IMessage<S_EVENT>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<S_EVENT> _parser = new pb::MessageParser<S_EVENT>(() => new S_EVENT());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<S_EVENT> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S_EVENT() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S_EVENT(S_EVENT other) : this() {
      sender_ = other.sender_ != null ? other.sender_.Clone() : null;
      eventCode_ = other.eventCode_;
      fixedData_ = other.fixedData_ != null ? other.fixedData_.Clone() : null;
      customData_ = other.customData_ != null ? other.customData_.Clone() : null;
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S_EVENT Clone() {
      return new S_EVENT(this);
    }

    /// <summary>Field number for the "sender" field.</summary>
    public const int SenderFieldNumber = 1;
    private global::Protocol.PlayerInfo sender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.PlayerInfo Sender {
      get { return sender_; }
      set {
        sender_ = value;
      }
    }

    /// <summary>Field number for the "eventCode" field.</summary>
    public const int EventCodeFieldNumber = 2;
    private int eventCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EventCode {
      get { return eventCode_; }
      set {
        eventCode_ = value;
      }
    }

    /// <summary>Field number for the "fixedData" field.</summary>
    public const int FixedDataFieldNumber = 3;
    private global::Protocol.Packs fixedData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Packs FixedData {
      get { return fixedData_; }
      set {
        fixedData_ = value;
      }
    }

    /// <summary>Field number for the "customData" field.</summary>
    public const int CustomDataFieldNumber = 4;
    private global::Protocol.CustomDic customData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.CustomDic CustomData {
      get { return customData_; }
      set {
        customData_ = value;
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 5;
    private global::Protocol.Result result_ = global::Protocol.Result.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as S_EVENT);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(S_EVENT other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Sender, other.Sender)) return false;
      if (EventCode != other.EventCode) return false;
      if (!object.Equals(FixedData, other.FixedData)) return false;
      if (!object.Equals(CustomData, other.CustomData)) return false;
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (sender_ != null) hash ^= Sender.GetHashCode();
      if (EventCode != 0) hash ^= EventCode.GetHashCode();
      if (fixedData_ != null) hash ^= FixedData.GetHashCode();
      if (customData_ != null) hash ^= CustomData.GetHashCode();
      if (Result != global::Protocol.Result.Success) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (sender_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Sender);
      }
      if (EventCode != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EventCode);
      }
      if (fixedData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FixedData);
      }
      if (customData_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CustomData);
      }
      if (Result != global::Protocol.Result.Success) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (sender_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Sender);
      }
      if (EventCode != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EventCode);
      }
      if (fixedData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FixedData);
      }
      if (customData_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CustomData);
      }
      if (Result != global::Protocol.Result.Success) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (sender_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Sender);
      }
      if (EventCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EventCode);
      }
      if (fixedData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FixedData);
      }
      if (customData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CustomData);
      }
      if (Result != global::Protocol.Result.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(S_EVENT other) {
      if (other == null) {
        return;
      }
      if (other.sender_ != null) {
        if (sender_ == null) {
          Sender = new global::Protocol.PlayerInfo();
        }
        Sender.MergeFrom(other.Sender);
      }
      if (other.EventCode != 0) {
        EventCode = other.EventCode;
      }
      if (other.fixedData_ != null) {
        if (fixedData_ == null) {
          FixedData = new global::Protocol.Packs();
        }
        FixedData.MergeFrom(other.FixedData);
      }
      if (other.customData_ != null) {
        if (customData_ == null) {
          CustomData = new global::Protocol.CustomDic();
        }
        CustomData.MergeFrom(other.CustomData);
      }
      if (other.Result != global::Protocol.Result.Success) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (sender_ == null) {
              Sender = new global::Protocol.PlayerInfo();
            }
            input.ReadMessage(Sender);
            break;
          }
          case 16: {
            EventCode = input.ReadInt32();
            break;
          }
          case 26: {
            if (fixedData_ == null) {
              FixedData = new global::Protocol.Packs();
            }
            input.ReadMessage(FixedData);
            break;
          }
          case 34: {
            if (customData_ == null) {
              CustomData = new global::Protocol.CustomDic();
            }
            input.ReadMessage(CustomData);
            break;
          }
          case 40: {
            Result = (global::Protocol.Result) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (sender_ == null) {
              Sender = new global::Protocol.PlayerInfo();
            }
            input.ReadMessage(Sender);
            break;
          }
          case 16: {
            EventCode = input.ReadInt32();
            break;
          }
          case 26: {
            if (fixedData_ == null) {
              FixedData = new global::Protocol.Packs();
            }
            input.ReadMessage(FixedData);
            break;
          }
          case 34: {
            if (customData_ == null) {
              CustomData = new global::Protocol.CustomDic();
            }
            input.ReadMessage(CustomData);
            break;
          }
          case 40: {
            Result = (global::Protocol.Result) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
