// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqJBAoGUmVzdWx0EgsKB1NVQ0NFU1MQ",
            "ABIKCgZGQUlMRUQQARIXChNTVUNDRVNTX1JPT01fQ1JFQVRFEAISFwoTU1VD",
            "Q0VTU19ST09NX0pPSU5FRBADEhgKFFNVQ0NFU1NfR1JPVVBfQ1JFQVRFEAQS",
            "GAoUU1VDQ0VTU19HUk9VUF9KT0lORUQQBRIfChtGQUlMRURfUk9PTV9OT1Rf",
            "RVhJU1RTX1JPT00QChIjCh9GQUlMRURfUk9PTV9BTFJFQURZX0VYSVNUU19S",
            "T09NEAsSGwoXRkFJTEVEX1JPT01fTk9UX0lOX1JPT00QDBIkCiBGQUlMRURf",
            "Uk9PTV9VU0VSU19MSU1JVF9FWENFRURFRBANEiEKHUZBSUxFRF9HUk9VUF9O",
            "T1RfRVhJU1RTX0dST1VQEBQSHQoZRkFJTEVEX0dST1VQX05PVF9JTl9HUk9V",
            "UBAVEiUKIUZBSUxFRF9HUk9VUF9BTFJFQURZX0VYSVNUU19HUk9VUBAWEhsK",
            "F0ZBSUxFRF9HUk9VUF9TQU1FX0dST1VQEBcSIgoeRkFJTEVEX0dST1VQX05P",
            "VF9FWElTVFNfUExBWUVSEBgSJgoiRkFJTEVEX0dST1VQX0FMUkVBRFlfRVhJ",
            "U1RTX1BMQVlFUhAZEiUKIUZBSUxFRF9PQkpFQ1RfVE9UQUxfU0laRV9PVkVS",
            "RkxPVxAaKmEKB1Byb3BzSUQSEgoOTVZfUFJPUFNfU1RBUlQQABIPCgtQT1NJ",
            "VElPTl8zRBABEg8KC1JPVEFUSU9OXzNEEAISDAoIU0NBTEVfM0QQAxISCgxN",
            "Vl9QUk9QU19FTkQQoI0GKjEKDk9iamVjdFN5bmNUeXBlEhAKDFBFUlNPTkFM",
            "X09XThAAEg0KCUdST1VQX09XThABKrQBCg1PcGVyYXRpb25Db2RlEg4KCkhF",
            "QVJUX0JFQVQQABIXChNST09NX0pPSU5fT1JfQ1JFQVRFEAESDgoKUk9PTV9M",
            "RUFWRRACEhwKGE9USEVSX0NMSUVOVF9ST09NX0pPSU5FRBADEhsKF09USEVS",
            "X0NMSUVOVF9ST09NX0xFQVZFEAQSDgoKR1JPVVBfTElTVBAFEg4KCkdST1VQ",
            "X0pPSU4QBhIPCgtSQUlTRV9FVkVOVBAHKs8BCglFdmVudENvZGUSFgoSQ0hB",
            "TkdFX0dST1VQX09XTkVSEAASHQoZT1RIRVJfQ0xJRU5UX0dST1VQX0pPSU5F",
            "RBABEhwKGE9USEVSX0NMSUVOVF9HUk9VUF9MRUFWRRACEhMKD0lOSVRJQUxf",
            "T0JKRUNUUxADEhcKE0FERF9ORVRXT1JLX09CSkVDVFMQBBIaChZSRU1PVkVf",
            "TkVUV09SS19PQkpFQ1RTEAUSGgoWVVBEQVRFX05FVFdPUktfT0JKRUNUUxAG",
            "EgcKA1JQQxAHKjEKCFBhcmFtS2V5EgwKCFBPU0lUSU9OEAASDAoIUk9UQVRJ",
            "T04QARIJCgVTQ0FMRRACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.Result), typeof(global::Protocol.PropsID), typeof(global::Protocol.ObjectSyncType), typeof(global::Protocol.OperationCode), typeof(global::Protocol.EventCode), typeof(global::Protocol.ParamKey), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 패킷 변수만 갖고는 실패 이유를 알기 어려우므로 Enum 을 통해 실패 이유를 전달
  /// 여기에 실패의 이유를 적는 Enum 을 추후에 컨텐츠 별로 추가하자.
  /// </summary>
  public enum Result {
    [pbr::OriginalName("SUCCESS")] Success = 0,
    [pbr::OriginalName("FAILED")] Failed = 1,
    /// <summary>
    /// Room 관련 성공
    /// </summary>
    [pbr::OriginalName("SUCCESS_ROOM_CREATE")] SuccessRoomCreate = 2,
    [pbr::OriginalName("SUCCESS_ROOM_JOINED")] SuccessRoomJoined = 3,
    /// <summary>
    /// Group 관련 성공
    /// </summary>
    [pbr::OriginalName("SUCCESS_GROUP_CREATE")] SuccessGroupCreate = 4,
    [pbr::OriginalName("SUCCESS_GROUP_JOINED")] SuccessGroupJoined = 5,
    /// <summary>
    /// Room 관련 에러
    /// </summary>
    [pbr::OriginalName("FAILED_ROOM_NOT_EXISTS_ROOM")] FailedRoomNotExistsRoom = 10,
    [pbr::OriginalName("FAILED_ROOM_ALREADY_EXISTS_ROOM")] FailedRoomAlreadyExistsRoom = 11,
    /// <summary>
    /// Player 가 Room 에 들어와 있지 않음
    /// </summary>
    [pbr::OriginalName("FAILED_ROOM_NOT_IN_ROOM")] FailedRoomNotInRoom = 12,
    /// <summary>
    /// 유저 수 제한 초과, 심각한 오류
    /// </summary>
    [pbr::OriginalName("FAILED_ROOM_USERS_LIMIT_EXCEEDED")] FailedRoomUsersLimitExceeded = 13,
    /// <summary>
    /// Group 관련 에러
    /// </summary>
    [pbr::OriginalName("FAILED_GROUP_NOT_EXISTS_GROUP")] FailedGroupNotExistsGroup = 20,
    /// <summary>
    /// 현재 Player 가 그룹 내에 있지 않음
    /// </summary>
    [pbr::OriginalName("FAILED_GROUP_NOT_IN_GROUP")] FailedGroupNotInGroup = 21,
    /// <summary>
    /// 추가하려는 그룹이 이미 존재
    /// </summary>
    [pbr::OriginalName("FAILED_GROUP_ALREADY_EXISTS_GROUP")] FailedGroupAlreadyExistsGroup = 22,
    [pbr::OriginalName("FAILED_GROUP_SAME_GROUP")] FailedGroupSameGroup = 23,
    /// <summary>
    /// 찾는 플레이어가 존재하지 않음
    /// </summary>
    [pbr::OriginalName("FAILED_GROUP_NOT_EXISTS_PLAYER")] FailedGroupNotExistsPlayer = 24,
    /// <summary>
    /// 추가하려는 플레이어가 이미 존재
    /// </summary>
    [pbr::OriginalName("FAILED_GROUP_ALREADY_EXISTS_PLAYER")] FailedGroupAlreadyExistsPlayer = 25,
    /// <summary>
    /// Object 관련 에러
    /// </summary>
    [pbr::OriginalName("FAILED_OBJECT_TOTAL_SIZE_OVERFLOW")] FailedObjectTotalSizeOverflow = 26,
  }

  public enum PropsID {
    [pbr::OriginalName("MV_PROPS_START")] MvPropsStart = 0,
    [pbr::OriginalName("POSITION_3D")] Position3D = 1,
    [pbr::OriginalName("ROTATION_3D")] Rotation3D = 2,
    [pbr::OriginalName("SCALE_3D")] Scale3D = 3,
    [pbr::OriginalName("MV_PROPS_END")] MvPropsEnd = 100000,
  }

  public enum ObjectSyncType {
    [pbr::OriginalName("PERSONAL_OWN")] PersonalOwn = 0,
    /// <summary>
    /// 이것을 움직일 수 있는 사람은 MasterClient
    /// </summary>
    [pbr::OriginalName("GROUP_OWN")] GroupOwn = 1,
  }

  public enum OperationCode {
    [pbr::OriginalName("HEART_BEAT")] HeartBeat = 0,
    [pbr::OriginalName("ROOM_JOIN_OR_CREATE")] RoomJoinOrCreate = 1,
    [pbr::OriginalName("ROOM_LEAVE")] RoomLeave = 2,
    [pbr::OriginalName("OTHER_CLIENT_ROOM_JOINED")] OtherClientRoomJoined = 3,
    [pbr::OriginalName("OTHER_CLIENT_ROOM_LEAVE")] OtherClientRoomLeave = 4,
    [pbr::OriginalName("GROUP_LIST")] GroupList = 5,
    [pbr::OriginalName("GROUP_JOIN")] GroupJoin = 6,
    [pbr::OriginalName("RAISE_EVENT")] RaiseEvent = 7,
  }

  public enum EventCode {
    [pbr::OriginalName("CHANGE_GROUP_OWNER")] ChangeGroupOwner = 0,
    [pbr::OriginalName("OTHER_CLIENT_GROUP_JOINED")] OtherClientGroupJoined = 1,
    [pbr::OriginalName("OTHER_CLIENT_GROUP_LEAVE")] OtherClientGroupLeave = 2,
    [pbr::OriginalName("INITIAL_OBJECTS")] InitialObjects = 3,
    [pbr::OriginalName("ADD_NETWORK_OBJECTS")] AddNetworkObjects = 4,
    [pbr::OriginalName("REMOVE_NETWORK_OBJECTS")] RemoveNetworkObjects = 5,
    [pbr::OriginalName("UPDATE_NETWORK_OBJECTS")] UpdateNetworkObjects = 6,
    [pbr::OriginalName("RPC")] Rpc = 7,
  }

  public enum ParamKey {
    [pbr::OriginalName("POSITION")] Position = 0,
    [pbr::OriginalName("ROTATION")] Rotation = 1,
    [pbr::OriginalName("SCALE")] Scale = 2,
  }

  #endregion

}

#endregion Designer generated code
